datasource_unique_name = "my datasource"
datasource_description = "my description"
datasource_username = "my username"
datasource_password = "my pass"
datasource_warehouse = "my warehouse"
datasource_role = "my role"
datasource_account = "my account"
datasource_database = "my database"
datasource_schema = "my schema"

datapool_unique_name = "my datapool"
datapool_description = "my description"
datapool_table = "sample"
datapool_timestamp = "created_at"