name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      PROPEL_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      PROPEL_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
      

    - name: Build
      run: go build -v ./...

    - name: Test
      run: TF_ACC=1 go test -v ./... -timeout 120m -parallel 3